from linked_list import LinkedList
from bidirectional_linked_list import BiLinkedList

# work with unidirectional linked list
print("Unidirectional linked list")
my_list = LinkedList()
my_list.append(2)
my_list.append(4)
my_list.append(8)
my_list.append(16)
my_list.show()
my_list.reverse()
my_list.show()
# my_list.length()
# my_list.push_front(9)
# my_list.show()
# my_list.length()
# my_list.remove_back()
# my_list.show()
# my_list.length()
# my_list.remove_front()
# my_list.show()
# my_list.length()
# print(f"my_list[1] = {my_list.value_at(1)}")
# print(f"my_list[9] = {my_list.value_at(9)}")
# my_list.insert(2, 9)
# my_list.show()
# my_list.remove(2)
# my_list.show()

# work with  bidirectional linked list
print("Bidirectional linked list")
bi_list = BiLinkedList()
bi_list.insert_in_emptylist(3)
bi_list.push_front(6)
bi_list.append(9)
bi_list.append(5)
bi_list.show()
bi_list.reverse()
bi_list.show()
# bi_list.length()
# bi_list.remove_front()
# bi_list.show()
# bi_list.remove_back()
# bi_list.show()
# bi_list.length()
